# Generated by Django 5.0.1 on 2024-01-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediceAcciones', '0002_alter_accion_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='identificador',
            field=models.CharField(max_length=20),
        ),
    ]
